// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCraftyStash.Data;

#nullable disable

namespace MyCraftyStash.Data.Migrations.Inventory
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MyCraftyStash.Models.AddressBookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("address_book", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date");

                    b.Property<TimeSpan?>("EventTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_time");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_all_day");

                    b.Property<bool>("ReminderDismissed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reminder_dismissed");

                    b.Property<int>("ReminderMinutesBefore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reminder_minutes_before");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("calendar_events", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.HiddenInspirationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_key");

                    b.HasKey("Id");

                    b.ToTable("hidden_inspiration_images", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultColors")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_colors");

                    b.Property<string>("DefaultItemIds")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSentiment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_sentiment");

                    b.Property<string>("DefaultSubtypes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTeColors")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_te_colors");

                    b.Property<string>("DefaultThemes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_themes");

                    b.Property<string>("DefaultTypes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_types");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentBoardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_board_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentBoardId");

                    b.ToTable("inspiration_boards", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BoardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("board_id");

                    b.Property<string>("Color")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiment");

                    b.Property<string>("TeColor")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("te_color");

                    b.Property<string>("Theme")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Types")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("types");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("inspiration_images", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationImageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("InspirationImageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inspiration_image_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("InspirationImageId");

                    b.HasIndex("ItemId");

                    b.ToTable("inspiration_image_items", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_stock");

                    b.Property<DateTime?>("DatePurchased")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_purchased");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDiscontinued")
                        .HasMaxLength(30)
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_discontinued");

                    b.Property<string>("ItemNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_number");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("PackSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pack_size");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("PurchasedFrom")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchased_from");

                    b.Property<string>("Sentiments")
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiments");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("site_url");

                    b.Property<int?>("StencilLayers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stencil_layers");

                    b.Property<string>("Subtype")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("subtype");

                    b.Property<string>("Theme")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("item_images", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DatePurchased")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_purchased");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_item");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("item_purchases", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemRelationship", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("RelatedItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("related_item_id");

                    b.HasKey("ItemId", "RelatedItemId");

                    b.HasIndex("RelatedItemId");

                    b.ToTable("item_relationships", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Technique")
                        .HasColumnType("TEXT")
                        .HasColumnName("technique");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCardBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CardBaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("card_base_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("StateSnapshot")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_card_builds", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCardBuildStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BuildId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("build_id");

                    b.Property<string>("CuttingMethod")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cutting_method");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int?>("MatLayer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mat_layer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("section");

                    b.Property<int?>("StackletDieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacklet_die_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("step_type");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StackletDieId");

                    b.ToTable("project_card_build_steps", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCreation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_on");

                    b.Property<string>("MaterialsUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("materials_used");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_creations", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_images", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountUsedPerCreation")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_used_per_creation");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_items", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.SentimentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ImageData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image_data");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("search_text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("sentiment_images", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.StackletDie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DieNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("die_number");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("height");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("stacklet_dies", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("ItemNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("PurchasedFrom")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchased_from");

                    b.Property<string>("Theme")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("theme");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<int?>("WishlistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wishlist_id");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationBoard", b =>
                {
                    b.HasOne("MyCraftyStash.Models.InspirationBoard", null)
                        .WithMany()
                        .HasForeignKey("ParentBoardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationImage", b =>
                {
                    b.HasOne("MyCraftyStash.Models.InspirationBoard", null)
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MyCraftyStash.Models.InspirationImageItem", b =>
                {
                    b.HasOne("MyCraftyStash.Models.InspirationImage", "InspirationImage")
                        .WithMany()
                        .HasForeignKey("InspirationImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspirationImage");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemImage", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemPurchase", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ItemRelationship", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany("RelatedFrom")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCraftyStash.Models.Item", "RelatedItem")
                        .WithMany("RelatedTo")
                        .HasForeignKey("RelatedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RelatedItem");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCardBuild", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCardBuildStep", b =>
                {
                    b.HasOne("MyCraftyStash.Models.ProjectCardBuild", "Build")
                        .WithMany("Steps")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyCraftyStash.Models.StackletDie", "StackletDie")
                        .WithMany()
                        .HasForeignKey("StackletDieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Build");

                    b.Navigation("Item");

                    b.Navigation("StackletDie");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCreation", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Project", "Project")
                        .WithMany("Creations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectImage", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectItem", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany("ProjectItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCraftyStash.Models.Project", "Project")
                        .WithMany("ProjectItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyCraftyStash.Models.SentimentImage", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyCraftyStash.Models.StackletDie", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyCraftyStash.Models.WishlistItem", b =>
                {
                    b.HasOne("MyCraftyStash.Models.Wishlist", null)
                        .WithMany()
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MyCraftyStash.Models.Item", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProjectItems");

                    b.Navigation("Purchases");

                    b.Navigation("RelatedFrom");

                    b.Navigation("RelatedTo");
                });

            modelBuilder.Entity("MyCraftyStash.Models.Project", b =>
                {
                    b.Navigation("Creations");

                    b.Navigation("Images");

                    b.Navigation("ProjectItems");
                });

            modelBuilder.Entity("MyCraftyStash.Models.ProjectCardBuild", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
