// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCraftyStash.Data;

#nullable disable

namespace MyCraftyStash.Data.Migrations.Settings
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260509040300_AddColorMatches")]
    partial class AddColorMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MyCraftyStash.Models.ColorMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("external_code");

                    b.Property<string>("ExternalHex")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_hex");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system");

                    b.Property<string>("TeColorHex")
                        .HasColumnType("TEXT")
                        .HasColumnName("te_color_hex");

                    b.Property<string>("TeColorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("te_color_name");

                    b.HasKey("Id");

                    b.HasIndex("System", "ExternalCode")
                        .IsUnique();

                    b.HasIndex("System", "TeColorName");

                    b.ToTable("color_matches", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.ConfigList", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.HasKey("Name");

                    b.ToTable("config_lists", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.CustomColor", b =>
                {
                    b.Property<string>("BrushKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("brush_key");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hex");

                    b.HasKey("BrushKey");

                    b.ToTable("custom_colors", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.KvSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("kv_settings", (string)null);
                });

            modelBuilder.Entity("MyCraftyStash.Models.TypeSortOrderEntry", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Sort1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort1");

                    b.Property<string>("Sort2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort2");

                    b.Property<string>("Sort3")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort3");

                    b.HasKey("Type");

                    b.ToTable("type_sort_orders", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
